apiVersion: bpfman.io/v1alpha1
kind: Config
metadata:
  name: config
spec:
  namespace: kube-system
  configuration: |
    [database]
    max_retries = 30
    millisec_delay = 10000
    [signing]
    allow_unsigned = true
    verify_enabled = true
  agent:
    image: quay.io/bpfman/bpfman-agent:latest
    logLevel: info
  daemon:
    image: quay.io/bpfman/bpfman:latest
    logLevel: info
